### ISSUE TITLE
Citation in Kevin Murphy's "Probabilistic Machine Learning: An Introduction"

### ISSUE THREAD

**Issue by DavidWalz** [valeman/awesome-conformal-prediction#10]
Thanks @valeman for this awesome list.

> Awesome Conformal Prediction has been cited in the best book on Machine Learning (aka the machine learning 'bible') [Probabilistic Machine Learning: An Introduction](https://probml.github.io/pml-book/book1.html) by the leading research scientist at Google (over 80K Google Scholar citations) and Bestselling Machine Learning Book Author Kevin Murphy.

Could you specify the reference? I could not find anything on conformal predictions.

**Comment by valeman** [comment]
HI @DavidWalz it is in the second part p555. I have amended accordingly, thank you. 

https://github.com/probml/pml2-book
