### ISSUE TITLE
Request to add the below content.

### ISSUE THREAD

**Issue by rahvis** [valeman/awesome-conformal-prediction#2]
I see somehow the patent section was missing in the repo (may have missed during the merge). Can I request you to please add them if it suits the purpose. 

Patents
-------

Rahul Vishwakarma, Method and system for reliably forecasting storage disk failure. US 2021/0034450 A1 United States Patent and Trademark Office, Feb 2021

Rahul Vishwakarma, Analyzing Time Series Data for Sets of Devices Using Machine Learning Techniques. US 2021/0241929 A1 United States Patent and Trademark Office, Aug 2021

Rahul Vishwakarma, System and method for prioritizing and preventing backup failures. US 2021/0374568 A1 United States Patent and Trademark Office, Dec 2021

**Comment by valeman** [comment]
Added
