### ISSUE TITLE
Conformal prediction and time series

### ISSUE THREAD

**Issue by yongqiang-zhao** [valeman/awesome-conformal-prediction#20]
Please correct me if my understanding is wrong. Conformal prediction is based on the assumption of data exchangeability. Since time series data are generally non exchangeable, we can not apply conformal prediction to time series data.

**Comment by matteo-fontana** [comment]
What you say is true, but there are several buts:

1. What you actually need is conditional exchangeability, so if you specifiy correctly your time series model (and thus have an IID error term...) you can apply CP and enjoy all the fancy finite-sample properties of the method , see e.g. http://proceedings.mlr.press/v75/chernozhukov18a.html
2.  If you violate exchangeability, you still have some theoretical guarantees in terms of coverage (that now becomes asymptotic), and simulations show that CP in this realm does in any case work quite quell (in the same paper I mentioned before).
3. There are works that aim to extend the finite sample properties of CP also in a non IID setting, see for instance a series of pubs by Rina Barber and coauthors where they do exactly that (e.g. https://arxiv.org/pdf/2202.13415.pdf)

Hope this answers your questions
