### ISSUE TITLE
Duplicate video entry

### ISSUE THREAD

**Issue by radlfabs** [valeman/awesome-conformal-prediction#34]
Hey there 👋 
Thanks for putting this together and maintaining with a high quality!

There seems to be a duplicate entry of a video URL in the README:
https://github.com/valeman/awesome-conformal-prediction/blob/1f6e3d8a0e6c40c90f3e55ba03081dc9b62d88db/README.md?plain=1#L263
which is the same as https://github.com/valeman/awesome-conformal-prediction/blob/1f6e3d8a0e6c40c90f3e55ba03081dc9b62d88db/README.md?plain=1#L259-L260

Best wishes!

**Comment by valeman** [comment]
Thank you.
