### ISSUE TITLE
Implementing Conformalized Quantile Regression

### ISSUE THREAD

**Issue by davitens** [valeman/awesome-conformal-prediction#35]
First of all, sorry for contacting using githubs issues. I couldn't find any other way. 
Second, congratulations for this repo. It's amazing.

I would like to know how to implement Conformalized Quantile Regression with "custom" algorithms. I tried MAPIE, but I could not manage to use CQR with Catboost. I saw and Issue Valery opened on Catboost repo, but it does not have an appropiate outcome. 

Thanks!

**Comment by valeman** [comment]
@davitens please use Slack for questions about CP, there is also channel for MAPIE questions there.
