### ISSUE TITLE
Conformal Prediction (for hierarchical Time Series)

### ISSUE THREAD

**Issue by katiavas** [valeman/awesome-conformal-prediction#38]
My question is can I sum up conformal bounds so that they maintain their validity?

More context i needed: I am using Ensemble batch prediction intervals (EnbPI) to output conformal upper and lower bounds for my time series data. I want to reconcile the upper bound and then the lower bound (input each one in the formula instead of y_pred) with MinTrace(or any otehr reconciliation method for that matter). Will this affect the validity coverage of my bounds or violate some assumptions? Or it is okay to sum up bounds like this ?

The reconciliation formula for inTrace if it helps: 
![image](https://github.com/valeman/awesome-conformal-prediction/assets/72811416/ef44dfc9-6158-4f36-ac7e-dc352928b690)

**Comment by valeman** [comment]
This repo is not for questions please use Slack for this.
